defaults:
  - physicsnemo_default
  - arch:
      - kan
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
arch:
  kan:
    layer_size: 20
    nr_layers: 3
    grid_size: 10
    spline_order: 3
    base_activation_fn: tanh
    grid_range: [-1, 1]
    domain_bounds: [[0.0, 1.0], [0.0, 2.56]]
    free_knot: true
scheduler:
  decay_rate: 0.85
  decay_steps: 4000
optimizer:
  lr: 1.0e-3

training:
  rec_results_freq: 2000
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  save_network_freq: 1000
  summary_freq: 1000
  max_steps : 50000
  print_stats_freq: 100
  grad_agg_freq: 1
  grad_clip_max_norm: 0.8
  ntk:
    use_ntk: false
    save_name: null
    run_freq: 10

batch_size:
  Initial: 2000
  Left: 2000
  Right: 2000
  Interior: 6000

hydra:
  job:
    chdir: true

cuda_graphs: true

graph:
  func_arch: true
  func_arch_allow_partial_hessian: true

custom:
  grid_sampling: false