# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults:
  - physicsnemo_default
  - arch:
      - full_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: brdr
  - _self_
arch:
  fully_connected:
    layer_size: 512
    nr_layers: 6
    activation_fn: tanh
    adaptive_activations: false
scheduler:
  decay_rate: 0.9
  decay_steps: 4000
optimizer:
  lr: 1.0e-3

training:
  rec_results_freq: 2000
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  save_network_freq: 1000
  summary_freq: 1000
  max_steps : 60000
  print_stats_freq: 100
  grad_agg_freq: 1
  grad_clip_max_norm: 0.8
  ntk:
    use_ntk: false
    save_name: null
    run_freq: 10

batch_size:
  Initial: 2000
  Left: 2000
  Right: 2000
  Interior: 6000

hydra:
  job:
    chdir: true

cuda_graphs: true

graph:
  func_arch: true
  func_arch_allow_partial_hessian: true

custom:
  grid_sampling: false
  sdf: true
  quasirandom: true